/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  RulesEngineClientCustom,
  RulesEngineClientCustomInterface,
} from "../../../contracts/RulesEngineIntegration.sol/RulesEngineClientCustom";

const _abi = [
  {
    inputs: [],
    name: "rulesEngineAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "callingContractAdmin",
        type: "address",
      },
    ],
    name: "setCallingContractAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "rulesEngine",
        type: "address",
      },
    ],
    name: "setRulesEngineAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class RulesEngineClientCustom__factory {
  static readonly abi = _abi;
  static createInterface(): RulesEngineClientCustomInterface {
    return new Interface(_abi) as RulesEngineClientCustomInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RulesEngineClientCustom {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as RulesEngineClientCustom;
  }
}
