/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAToken } from "./MockAToken";
export type { MockAsset } from "./MockAsset";
export type { MockLendingPool } from "./MockLendingPool";
