[package]
name = "openbanking"
type = "bin"
authors = [""]

[dependencies]
bignum = {tag = "v0.5.0", git = "https://github.com/noir-lang/noir-bignum"}
json_parser = { tag = "main", git = "https://github.com/noir-lang/noir_json_parser"}
rsa_pss = { git = "https://github.com/jp4g/noir_rsa_pss", tag = "feat/nargo-1.0.0", directory = "lib" }
zkemail = { git = "https://github.com/zkemail/zkemail.nr", tag = "v0.4.1", directory = "lib"} 