/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  OfacSanction,
  OfacSanctionInterface,
} from "../../../contracts/Escrow.sol/OfacSanction";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "blacklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isBlacklisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "register",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061025b8061001f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80633af32abf146100515780634420e48614610088578063f9f92be41461009d578063fe575a87146100e1575b600080fd5b61007461005f3660046101f5565b60016020526000908152604090205460ff1681565b604051901515815260200160405180910390f35b61009b6100963660046101f5565b610104565b005b61009b6100ab3660046101f5565b6001600160a01b03166000908152600160208181526040808420805460ff19908116909155918490529092208054909216179055565b6100746100ef3660046101f5565b60006020819052908152604090205460ff1681565b6001600160a01b038116331461016f5760405162461bcd60e51b815260206004820152602560248201527f4f6e6c792074686520757365722063616e207265676973746572207468656d73604482015264656c76657360d81b60648201526084015b60405180910390fd5b6001600160a01b03811660009081526020819052604090205460ff16156101ce5760405162461bcd60e51b8152602060048201526013602482015272155cd95c881a5cc8189b1858dadb1a5cdd1959606a1b6044820152606401610166565b6001600160a01b03166000908152600160208190526040909120805460ff19169091179055565b60006020828403121561020757600080fd5b81356001600160a01b038116811461021e57600080fd5b939250505056fea2646970667358221220a3b4d33a8e8c2976cdce26b279dc8a6b225207e1c5357713480b904298c3126864736f6c634300081b0033";

type OfacSanctionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OfacSanctionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OfacSanction__factory extends ContractFactory {
  constructor(...args: OfacSanctionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      OfacSanction & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): OfacSanction__factory {
    return super.connect(runner) as OfacSanction__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OfacSanctionInterface {
    return new Interface(_abi) as OfacSanctionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): OfacSanction {
    return new Contract(address, _abi, runner) as unknown as OfacSanction;
  }
}
