/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IRulesEngineInterface extends Interface {
  getFunction(
    nameOrSignature: "checkPolicies" | "grantCallingContractRole"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkPolicies",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantCallingContractRole",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantCallingContractRole",
    data: BytesLike
  ): Result;
}

export interface IRulesEngine extends BaseContract {
  connect(runner?: ContractRunner | null): IRulesEngine;
  waitForDeployment(): Promise<this>;

  interface: IRulesEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkPolicies: TypedContractMethod<
    [contractAddress: AddressLike, arguments: BytesLike],
    [bigint],
    "nonpayable"
  >;

  grantCallingContractRole: TypedContractMethod<
    [_callingContract: AddressLike, _account: AddressLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkPolicies"
  ): TypedContractMethod<
    [contractAddress: AddressLike, arguments: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantCallingContractRole"
  ): TypedContractMethod<
    [_callingContract: AddressLike, _account: AddressLike],
    [string],
    "nonpayable"
  >;

  filters: {};
}
