/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  OfacSanction,
  OfacSanctionInterface,
} from "../../../contracts/MockOfacSanction.sol/OfacSanction";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "blacklist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isBlacklisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isWhitelisted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061014c8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80633af32abf14610046578063f9f92be41461007d578063fe575a87146100c3575b600080fd5b6100696100543660046100e6565b60016020526000908152604090205460ff1681565b604051901515815260200160405180910390f35b6100c161008b3660046100e6565b6001600160a01b03166000908152600160208181526040808420805460ff19908116909155918490529092208054909216179055565b005b6100696100d13660046100e6565b60006020819052908152604090205460ff1681565b6000602082840312156100f857600080fd5b81356001600160a01b038116811461010f57600080fd5b939250505056fea2646970667358221220d84b63f4f96ae7dc802efab93168cce63c76a07592957efa15362f4a21d7761264736f6c634300081b0033";

type OfacSanctionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OfacSanctionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OfacSanction__factory extends ContractFactory {
  constructor(...args: OfacSanctionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      OfacSanction & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): OfacSanction__factory {
    return super.connect(runner) as OfacSanction__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OfacSanctionInterface {
    return new Interface(_abi) as OfacSanctionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): OfacSanction {
    return new Contract(address, _abi, runner) as unknown as OfacSanction;
  }
}
